version: '2'
services:
  container:
    container_name: example_container_prod
    build:
      context: .
      dockerfile: container/Dockerfile
    environment:
      - PORT=3000
    ports:
      - '3000:3000'