version: '2'
services:
  container:
    container_name: example_container
    image: node:lts
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    volumes:
      - './container/built:/app'
  dns:
    container_name: dns-lookup
    image: node:lts
    ports:
      - '4000:3000'
    volumes:
      - './dns-lookup:/app'
    working_dir: '/app'
    command: 'yarn dev'
